apiVersion: v2
name: pgweb
description: A Helm chart for pgweb
type: application
version: 1.3.0
appVersion: 0.17.0
keywords:
  - postgres
  - database
  - http-server
  - ui
sources:
  - https://github.com/sosedoff/pgweb
maintainers:
  - name: lrstanley
    email: liam@liam.sh
    url: https://liam.sh
